### ISSUE TITLE
Global Variables are ignored

### ISSUE THREAD

**Issue by webdesserts** [mxstbr/react-boilerplate#282]
If you try to define a variable like so:

```css
/* Global Variables */
:global :root {
  --bkg: red;
}

/* Local Variables */
:root {
  --color: blue;
}

html {
  background-color: var(--bkg);
  color: var(--color);
}

```

You will get the following error back from webpack:

```
app/containers/App/styles.css
4:3       Custom property ignored: not scoped to the top-level :root element (:global :root { ... --bkg: ... }) [postcss-custom-properties]
12:3      variable '--bkg' is undefined and used without a fallback [postcss-custom-properties]
```
And a response that looks like this:

```css
/* Global Variables */
:root {
  --bkg: red;
}

/* Local Variables */

html {
  background-color: var(--bkg);
  color: blue;
}

```

Essentially postcss-custom-properties looks for `:root` specifically and if it finds a variable in any other scope, it leaves the variable as is and doesn't touch it. When it sees `:global :root` it automatically assumes it's not the right scope and moves on.

This prevents a dev from add global variables such as theme colors and similar that can be reused across files.
