### ISSUE TITLE
How to import a single variables file ?

### ISSUE THREAD

**Issue by suhaotian** [mxstbr/react-boilerplate#535]
It's useful for style, but I didn't seem support in this boilerplate.

**Comment by mxstbr** [comment]
I'm not sure I understand the question here, would you mind explaining what a "single variables file" is in this case? Like constants?

**Comment by suhaotian** [comment]
👍 😄  Thank you for your support to!
For example, I have a variables file **colors.css**:
```css
:root {
  --default: #5bc0de;
  --success: #8add6d;
  --danger: #d9534f;
}
```
It's useful for style, But I don't know how to use it in other's file, 😢
